/*
 * Copyright 2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package griffon.plugins.fontawesome;

import griffon.util.GriffonNameUtils;

/**
 * @author Andres Almiray
 */
public enum FontAwesome {
    ICON_GLASS("icon-glass", '\uf000'),
    ICON_MUSIC("icon-music", '\uf001'),
    ICON_SEARCH("icon-search", '\uf002'),
    ICON_ENVELOPE_ALT("icon-envelope-alt", '\uf003'),
    ICON_HEART("icon-heart", '\uf004'),
    ICON_STAR("icon-star", '\uf005'),
    ICON_STAR_EMPTY("icon-star-empty", '\uf006'),
    ICON_USER("icon-user", '\uf007'),
    ICON_FILM("icon-film", '\uf008'),
    ICON_TH_LARGE("icon-th-large", '\uf009'),
    ICON_TH("icon-th", '\uf00a'),
    ICON_TH_LIST("icon-th-list", '\uf00b'),
    ICON_OK("icon-ok", '\uf00c'),
    ICON_REMOVE("icon-remove", '\uf00d'),
    ICON_ZOOM_IN("icon-zoom-in", '\uf00e'),
    ICON_ZOOM_OUT("icon-zoom-out", '\uf010'),
    ICON_OFF("icon-off", '\uf011'),
    ICON_SIGNAL("icon-signal", '\uf012'),
    ICON_COG("icon-cog", '\uf013'),
    ICON_TRASH("icon-trash", '\uf014'),
    ICON_HOME("icon-home", '\uf015'),
    ICON_FILE_AT("icon-file-alt", '\uf016'),
    ICON_TIME("icon-time", '\uf017'),
    ICON_ROAD("icon-road", '\uf018'),
    ICON_DOWNLOAD_ALT("icon-download-alt", '\uf019'),
    ICON_DOWNLOAD("icon-download", '\uf01a'),
    ICON_UPLOAD("icon-upload", '\uf01b'),
    ICON_INBOX("icon-inbox", '\uf01c'),
    ICON_PLAY_CIRCLE("icon-play-circle", '\uf01d'),
    ICON_REPEAT("icon-repeat", '\uf01e'),
    ICON_REFRESH("icon-refresh", '\uf021'),
    ICON_LIST_ALT("icon-list-alt", '\uf022'),
    ICON_LOCK("icon-lock", '\uf023'),
    ICON_FLAG("icon-flag", '\uf024'),
    ICON_HEADPHONES("icon-headphones", '\uf025'),
    ICON_VOLUME_OFF("icon-volume-off", '\uf026'),
    ICON_VOLUME_DOWN("icon-volume-down", '\uf027'),
    ICON_VOLUME_UP("icon-volume-up", '\uf028'),
    ICON_QRCODE("icon-qrcode", '\uf029'),
    ICON_BARCODE("icon-barcode", '\uf02a'),
    ICON_TAG("icon-tag", '\uf02b'),
    ICON_TAGS("icon-tags", '\uf02c'),
    ICON_BOOK("icon-book", '\uf02d'),
    ICON_BOOKMARK("icon-bookmark", '\uf02e'),
    ICON_PRINT("icon-print", '\uf02f'),
    ICON_CAMERA("icon-camera", '\uf030'),
    ICON_FONT("icon-font", '\uf031'),
    ICON_BOLD("icon-bold", '\uf032'),
    ICON_ITALIC("icon-italic", '\uf033'),
    ICON_TEXT_HEIGHT("icon-text-height", '\uf034'),
    ICON_TEXT_WIDTH("icon-text-width", '\uf035'),
    ICON_ALIGN_LEFT("icon-align-left", '\uf036'),
    ICON_ALIGN_CENTER("icon-align-center", '\uf037'),
    ICON_ALIGN_RIGHT("icon-align-right", '\uf038'),
    ICON_ALIGN_JUSTIFY("icon-align-justify", '\uf039'),
    ICON_LIST("icon-list", '\uf03a'),
    ICON_INDENT_LEFT("icon-indent-left", '\uf03b'),
    ICON_INDENT_RIGHT("icon-indent-right", '\uf03c'),
    ICON_FACETIME_VIDEO("icon-facetime-video", '\uf03d'),
    ICON_PICTURE("icon-picture", '\uf03e'),
    ICON_PENCIL("icon-pencil", '\uf040'),
    ICON_MAP_MARKER("icon-map-marker", '\uf041'),
    ICON_ADJUST("icon-adjust", '\uf042'),
    ICON_TINT("icon-tint", '\uf043'),
    ICON_EDIT("icon-edit", '\uf044'),
    ICON_SHARE("icon-share", '\uf045'),
    ICON_CHECK("icon-check", '\uf046'),
    ICON_MOVE("icon-move", '\uf047'),
    ICON_STEP_BACKWARD("icon-step-backward", '\uf048'),
    ICON_FAST_BACKWARD("icon-fast-backward", '\uf049'),
    ICON_BACKWARD("icon-backward", '\uf04a'),
    ICON_PLAY("icon-play", '\uf04b'),
    ICON_PAUSE("icon-pause", '\uf04c'),
    ICON_STOP("icon-stop", '\uf04d'),
    ICON_FORWARD("icon-forward", '\uf04e'),
    ICON_FAST_FORWARD("icon-fast-forward", '\uf050'),
    ICON_STEP_FORWARD("icon-step-forward", '\uf051'),
    ICON_EJECT("icon-eject", '\uf052'),
    ICON_CHEVRON_RIGHT("icon-chevron-left", '\uf053'),
    ICON_CHEVRON_LEFT("icon-chevron-right", '\uf054'),
    ICON_PLUS_SIGN("icon-plus-sign", '\uf055'),
    ICON_MINUS_SIGN("icon-minus-sign", '\uf056'),
    ICON_REMOVE_SIGN("icon-remove-sign", '\uf057'),
    ICON_OK_SIGN("icon-ok-sign", '\uf058'),
    ICON_QUESTION_SIGN("icon-question-sign", '\uf059'),
    ICON_INFO_SIGN("icon-info-sign", '\uf05a'),
    ICON_SCREENSHOT("icon-screenshot", '\uf05b'),
    ICON_REMOVE_CIRCLE("icon-remove-circle", '\uf05c'),
    ICON_OK_CIRCLE("icon-ok-circle", '\uf05d'),
    ICON_BAN_CIRCLE("icon-ban-circle", '\uf05e'),
    ICON_ARROW_CIRCLE("icon-arrow-left", '\uf060'),
    ICON_ARROW_RIGHT("icon-arrow-right", '\uf061'),
    ICON_ARROW_UP("icon-arrow-up", '\uf062'),
    ICON_ARROWN_DOWN("icon-arrow-down", '\uf063'),
    ICON_SHARE_ALT("icon-share-alt", '\uf064'),
    ICON_RESIZE_FULL("icon-resize-full", '\uf065'),
    ICON_RESIZE_SMALL("icon-resize-small", '\uf066'),
    ICON_PLSU("icon-plus", '\uf067'),
    ICON_MINUS("icon-minus", '\uf068'),
    ICON_ASTERISK("icon-asterisk", '\uf069'),
    ICON_EXCLAMATION_SIGN("icon-exclamation-sign", '\uf06a'),
    ICON_GIFT("icon-gift", '\uf06b'),
    ICON_LEAF("icon-leaf", '\uf06c'),
    ICON_FIRE("icon-fire", '\uf06d'),
    ICON_EYE_OPEN("icon-eye-open", '\uf06e'),
    ICON_EYE_CLOSE("icon-eye-close", '\uf070'),
    ICON_WARNING_SIGN("icon-warning-sign", '\uf071'),
    ICON_PLANE("icon-plane", '\uf072'),
    ICON_CALENDAR("icon-calendar", '\uf073'),
    ICON_RANDOM("icon-random", '\uf074'),
    ICON_COMMENT("icon-comment", '\uf075'),
    ICON_MAGNET("icon-magnet", '\uf076'),
    ICON_CHEVRON_UP("icon-chevron-up", '\uf077'),
    ICON_CHEVRON_DOWN("icon-chevron-down", '\uf078'),
    ICON_RETWEET("icon-retweet", '\uf079'),
    ICON_SHOPPING_CART("icon-shopping-cart", '\uf07a'),
    ICON_FOLDER_CLOSE("icon-folder-close", '\uf07b'),
    ICON_FOLDER_OPEN("icon-folder-open", '\uf07c'),
    ICON_RESIZE_VERTICAL("icon-resize-vertical", '\uf07d'),
    ICON_RESIZE_HORIZONTAL("icon-resize-horizontal", '\uf07e'),
    ICON_BAR_CHART("icon-bar-chart", '\uf080'),
    ICON_TWITER_SIGN("icon-twitter-sign", '\uf081'),
    ICON_FACEBOOK_SIGN("icon-facebook-sign", '\uf082'),
    ICON_CAMERA_RETRO("icon-camera-retro", '\uf083'),
    ICON_KEY("icon-key", '\uf084'),
    ICON_COGS("icon-cogs", '\uf085'),
    ICON_COMMENTS("icon-comments", '\uf086'),
    ICON_THUMBS_UP_ALT("icon-thumbs-up-alt", '\uf087'),
    ICON_THUMBS_DOWN_ALT("icon-thumbs-down-alt", '\uf088'),
    ICON_STAR_HALF("icon-star-half", '\uf089'),
    ICON_HEART_EMPTY("icon-heart-empty", '\uf08a'),
    ICON_SIGNOUT("icon-signout", '\uf08b'),
    ICON_LINKEDIN_SIGN("icon-linkedin-sign", '\uf08c'),
    ICON_PUSHPIN("icon-pushpin", '\uf08d'),
    ICON_EXTERNAL_LINK("icon-external-link", '\uf08e'),
    ICON_SIGNIN("icon-signin", '\uf090'),
    ICON_THROPHY("icon-trophy", '\uf091'),
    ICON_GITHUB_SIGN("icon-github-sign", '\uf092'),
    ICON_UPLOAD_ALT("icon-upload-alt", '\uf093'),
    ICON_LEMON("icon-lemon", '\uf094'),
    ICON_PHONE("icon-phone", '\uf095'),
    ICON_CHECK_EMPTY("icon-check-empty", '\uf096'),
    ICON_BOOKMARK_EMPTY("icon-bookmark-empty", '\uf097'),
    ICON_PHONE_SIGN("icon-phone-sign", '\uf098'),
    ICON_TWITTER("icon-twitter", '\uf099'),
    ICON_FACEBOOK("icon-facebook", '\uf09a'),
    ICON_GITHUB("icon-github", '\uf09b'),
    ICON_UNLOCK("icon-unlock", '\uf09c'),
    ICON_CREDIT_CARD("icon-credit-card", '\uf09d'),
    ICON_RSS("icon-rss", '\uf09e'),
    ICON_HDD("icon-hdd", '\uf0a0'),
    ICON_BULLHORN("icon-bullhorn", '\uf0a1'),
    ICON_BELL("icon-bell", '\uf0a2'),
    ICON_CERTIFICATE("icon-certificate", '\uf0a3'),
    ICON_HAND_RIGHT("icon-hand-right", '\uf0a4'),
    ICON_HAND_LEFT("icon-hand-left", '\uf0a5'),
    ICON_HAND_UP("icon-hand-up", '\uf0a6'),
    ICON_HAND_DOWN("icon-hand-down", '\uf0a7'),
    ICON_CIRCLE_ARROW_LEFT("icon-circle-arrow-left", '\uf0a8'),
    ICON_CIRCLE_ARROW_RIGHT("icon-circle-arrow-right", '\uf0a9'),
    ICON_CIRCLE_ARROW_UP("icon-circle-arrow-up", '\uf0aa'),
    ICON_CIRCLE_ARROW_DOWN("icon-circle-arrow-down", '\uf0ab'),
    ICON_GLOBE("icon-globe", '\uf0ac'),
    ICON_WRENCH("icon-wrench", '\uf0ad'),
    ICON_TASKS("icon-tasks", '\uf0ae'),
    ICON_FILTER("icon-filter", '\uf0b0'),
    ICON_BRIEFCASE("icon-briefcase", '\uf0b1'),
    ICON_FULLSCREEN("icon-fullscreen", '\uf0b2'),
    ICON_GROUP("icon-group", '\uf0c0'),
    ICON_LINK("icon-link", '\uf0c1'),
    ICON_CLOUD("icon-cloud", '\uf0c2'),
    ICON_BEAKER("icon-beaker", '\uf0c3'),
    ICON_CUT("icon-cut", '\uf0c4'),
    ICON_COPY("icon-copy", '\uf0c5'),
    ICON_PAER_CLIP("icon-paper-clip", '\uf0c6'),
    ICON_SAVE("icon-save", '\uf0c7'),
    ICON_SIGN_BANK("icon-sign-blank", '\uf0c8'),
    ICON_REORDER("icon-reorder", '\uf0c9'),
    ICON_LIST_UL("icon-list-ul", '\uf0ca'),
    ICON_LIST_OL("icon-list-ol", '\uf0cb'),
    ICON_STRIKETHROUGH("icon-strikethrough", '\uf0cc'),
    ICON_UNDERLINE("icon-underline", '\uf0cd'),
    ICON_TABLE("icon-table", '\uf0ce'),
    ICON_MAGIC("icon-magic", '\uf0d0'),
    ICON_TRUCK("icon-truck", '\uf0d1'),
    ICON_PINTEREST("icon-pinterest", '\uf0d2'),
    ICON_PINTEREST_SIGN("icon-pinterest-sign", '\uf0d3'),
    ICON_GOOGLE_PLUS_SIGN("icon-google-plus-sign", '\uf0d4'),
    ICON_GOOGLE_PLUS("icon-google-plus", '\uf0d5'),
    ICON_MONEY("icon-money", '\uf0d6'),
    ICON_CARET_DOWN("icon-caret-down", '\uf0d7'),
    ICON_CARET_UP("icon-caret-up", '\uf0d8'),
    ICON_CARET_LEFT("icon-caret-left", '\uf0d9'),
    ICON_CARET_RIGHT("icon-caret-right", '\uf0da'),
    ICON_COLUMNS("icon-columns", '\uf0db'),
    ICON_SORT("icon-sort", '\uf0dc'),
    ICON_SORT_DOWN("icon-sort-down", '\uf0dd'),
    ICON_SORT_UP("icon-sort-up", '\uf0de'),
    ICON_ENVELOPE("icon-envelope", '\uf0e0'),
    ICON_LINKEDIN("icon-linkedin", '\uf0e1'),
    ICON_UNDO("icon-undo", '\uf0e2'),
    ICON_LEGAL("icon-legal", '\uf0e3'),
    ICON_DASHBOARD("icon-dashboard", '\uf0e4'),
    ICON_COMMENT_ALT("icon-comment-alt", '\uf0e5'),
    ICON_COMMENTS_ALT("icon-comments-alt", '\uf0e6'),
    ICON_BOLT("icon-bolt", '\uf0e7'),
    ICON_SITEMAP("icon-sitemap", '\uf0e8'),
    ICON_UMBRELLA("icon-umbrella", '\uf0e9'),
    ICON_PASTE("icon-paste", '\uf0ea'),
    ICON_LIGHTBULB("icon-lightbulb", '\uf0eb'),
    ICON_EXCHANGE("icon-exchange", '\uf0ec'),
    ICON_CLOUD_DOWNLOAD("icon-cloud-download", '\uf0ed'),
    ICON_CLOUD_UPLOAD("icon-cloud-upload", '\uf0ee'),
    ICON_USER_MD("icon-user-md", '\uf0f0'),
    ICON_STETHOSCOPE("icon-stethoscope", '\uf0f1'),
    ICON_SUITCASE("icon-suitcase", '\uf0f2'),
    ICON_BELL_ALT("icon-bell-alt", '\uf0f3'),
    ICON_COFFEE("icon-coffee", '\uf0f4'),
    ICON_FOOD("icon-food", '\uf0f5'),
    ICON_FILE_TEXT_ALT("icon-file-text-alt", '\uf0f6'),
    ICON_BUILDING("icon-building", '\uf0f7'),
    ICON_HOSPITAL("icon-hospital", '\uf0f8'),
    ICON_AMBULANCE("icon-ambulance", '\uf0f9'),
    ICON_MEDKIT("icon-medkit", '\uf0fa'),
    ICON_FIGHTER_JET("icon-fighter-jet", '\uf0fb'),
    ICON_BEER("icon-beer", '\uf0fc'),
    ICON_H_SIGN("icon-h-sign", '\uf0fd'),
    ICON_PLUS_SIGN_ALT("plus-sign-alt", '\uf0fe'),
    ICON_DOUBLE_ANGLE_LEFT("icon-double-angle-left", '\uf100'),
    ICON_DOUBLE_ANGLE_RIGHT("icon-double-angle-right", '\uf101'),
    ICON_DOUBLE_ANGLE_UP("icon-double-angle-up", '\uf102'),
    ICON_DOUBLE_ANGLE_DOWN("icon-double-angle-down", '\uf103'),
    ICON_ANGLE_LEFT("icon-angle-left", '\uf104'),
    ICON_ANGLE_RIGHT("icon-angle-right", '\uf105'),
    ICON_ANGLE_UP("icon-angle-up", '\uf106'),
    ICON_ANGLE_DOWN("icon-angle-down", '\uf107'),
    ICON_DESKTOP("icon-desktop", '\uf108'),
    ICON_LAPTOP("icon-laptop", '\uf109'),
    ICON_TABLET("icon-tablet", '\uf10a'),
    ICON_MOBILE_PHONE("icon-mobile-phone", '\uf10b'),
    ICON_CIRCLE_BLANK("icon-circle-blank", '\uf10c'),
    ICON_QUOTE_LEFT("icon-quote-left", '\uf10d'),
    ICON_QUOTE_RIGHT("icon-quote-right", '\uf10e'),
    ICON_SPINNER("icon-spinner", '\uf110'),
    ICON_CIRCLE("icon-circle", '\uf111'),
    ICON_REPLY("icon-reply", '\uf112'),
    ICON_GITHUB_ALT("icon-github-alt", '\uf113'),
    ICON_FOLDER_CLOSE_ALT("icon-folder-close-alt", '\uf114'),
    ICON_FOLDER_OPEN_ALT("icon-folder-open-alt", '\uf115'),
    ICON_EXPAND_ALT("icon-expand-alt", '\uf116'),
    ICON_COLLAPSE_ALT("icon-collapse-alt", '\uf117'),
    ICON_SMILE("icon-smile", '\uf118'),
    ICON_FROWN("icon-frown", '\uf119'),
    ICON_MEH("icon-meh", '\uf11a'),
    ICON_GAMEPAD("icon-gamepad", '\uf11b'),
    ICON_KEYBOARD("icon-keyboard", '\uf11c'),
    ICON_FLAG_ALT("icon-flag-alt", '\uf11d'),
    ICON_FLAG_CHECKERED("icon-flag-checkered", '\uf11e'),
    ICON_TERMINAL("icon-terminal", '\uf120'),
    ICON_CODE("icon-code", '\uf121'),
    ICON_REPLY_ALL("icon-reply-all", '\uf122'),
    ICON_MAL_REPLY_ALL("icon-mail-reply-all", '\uf122'),
    ICON_STAR_HALF_EMPTY("icon-star-half-empty", '\uf123'),
    ICON_LOCATION_ARROW("icon-location-arrow", '\uf124'),
    ICON_CROP("icon-crop", '\uf125'),
    ICON_CODE_FORK("icon-code-fork", '\uf126'),
    ICON_UNLINK("icon-unlink", '\uf127'),
    ICON_QUESTION("icon-question", '\uf128'),
    ICON_INFO("icon-info", '\uf129'),
    ICON_EXCLAMATION("icon-exclamation", '\uf12a'),
    ICON_SUPERSCRIPT("icon-superscript", '\uf12b'),
    ICON_SUBSCRIPT("icon-subscript", '\uf12c'),
    ICON_ERASER("icon-eraser", '\uf12d'),
    ICON_PUZZLE_PIECE("icon-puzzle-piece", '\uf12e'),
    ICON_MICROPHONE("icon-microphone", '\uf130'),
    ICON_MICROPHONE_OFF("icon-microphone-off", '\uf131'),
    ICON_SHIELD("icon-shield", '\uf132'),
    ICON_CALENDAR_EMPTY("icon-calendar-empty", '\uf133'),
    ICON_FIRE_EXTINGUISHER("icon-fire-extinguisher", '\uf134'),
    ICON_ROCKET("icon-rocket", '\uf135'),
    ICON_MAXCDN("icon-maxcdn", '\uf136'),
    ICON_CHEVRON_SIGN_LEFT("icon-chevron-sign-left", '\uf137'),
    ICON_CHEVRON_SIGN_RIGHT("icon-chevron-sign-right", '\uf138'),
    ICON_CHEVRON_SIGN_UP("icon-chevron-sign-up", '\uf139'),
    ICON_CHEVRON_SIGN_DOWN("icon-chevron-sign-down", '\uf13a'),
    ICON_HTML5("icon-html5", '\uf13b'),
    ICON_CSS3("icon-css3", '\uf13c'),
    ICON_ANCHOR("icon-anchor", '\uf13d'),
    ICON_UNLOCK_ALL("icon-unlock-alt", '\uf13e'),
    ICON_BULLSEYE("icon-bullseye", '\uf140'),
    ICON_ELLIPSIS_HORIZONTAL("icon-ellipsis-horizontal", '\uf141'),
    ICON_ELLIPSIS_VERTICAL("icon-ellipsis-vertical", '\uf142'),
    ICON_RSS_SIGN("icon-rss-sign", '\uf143'),
    ICON_PLAY_SIGN("icon-play-sign", '\uf144'),
    ICON_TICKET("icon-ticket", '\uf145'),
    ICON_MINUS_SIGN_ALT("icon-minus-sign-alt", '\uf146'),
    ICON_CHECK_MINUS("icon-check-minus", '\uf147'),
    ICON_LEVEL_UP("icon-level-up", '\uf148'),
    ICON_LEVEL_DOWN("icon-level-down", '\uf149'),
    ICON_CHECK_SIGN("icon-check-sign", '\uf14a'),
    ICON_EDIT_SIGN("icon-edit-sign", '\uf14b'),
    ICON_EXTERNAL_LINK_SIGN("icon-external-link-sign", '\uf14c'),
    ICON_SHARE_SIGN("icon-share-sign", '\uf14d'),
    ICON_COMPASS("icon-compass", '\uf14e'),
    ICON_COLLAPSE("icon-collapse", '\uf150'),
    ICON_COLLAPSE_TOP("icon-collapse-top", '\uf151'),
    ICON_EXPAND("icon-expand", '\uf152'),
    ICON_EUR("icon-eur", '\uf153'),
    ICON_GBP("icon-gbp", '\uf154'),
    ICON_USD("icon-usd", '\uf155'),
    ICON_INR("icon-inr", '\uf156'),
    ICON_JPY("icon-jpy", '\uf157'),
    ICON_CNY("icon-cny", '\uf158'),
    ICON_KRW("icon-krw", '\uf159'),
    ICON_BTC("icon-btc", '\uf15a'),
    ICON_FILE("icon-file", '\uf15b'),
    ICON_FILE_TEXT("icon-file-text", '\uf15c'),
    ICON_SORT_BY_ALPHABET("icon-sort-by-alphabet", '\uf15d'),
    ICON_SORT_BY_ALPHABET_ALT("icon-sort-by-alphabet-alt", '\uf15e'),
    ICON_SORT_BY_ATTRIBUTES("icon-sort-by-attributes", '\uf160'),
    ICON_SORT_BY_ATTRIBUTES_ALT("icon-sort-by-attributes-alt", '\uf161'),
    ICON_SORT_BY_ORDER("icon-sort-by-order", '\uf162'),
    ICON_SORT_BY_ORDER_ALT("icon-sort-by-order-alt", '\uf163'),
    ICON_THUMBS_UP("icon-thumbs-up", '\uf164'),
    ICON_THUMBS_DPWN("icon-thumbs-down", '\uf165'),
    ICON_YOUTUBE_SIGN("icon-youtube-sign", '\uf166'),
    ICON_YOUTUBE("icon-youtube", '\uf167'),
    ICON_XING("icon-xing", '\uf168'),
    ICON_XING_SIGN("icon-xing-sign", '\uf169'),
    ICON_YOUTUBE_PLAY("icon-youtube-play", '\uf16a'),
    ICON_DROPBOX("icon-dropbox", '\uf16b'),
    ICON_STACKEXCHANGE("icon-stackexchange", '\uf16c'),
    ICON_INSTAGRAM("icon-instagram", '\uf16d'),
    ICON_FLICKR("icon-flickr", '\uf16e'),
    ICON_ADN("icon-adn", '\uf170'),
    ICON_BITBUCKET("icon-bitbucket", '\uf171'),
    ICON_BITBUCKET_SIGN("icon-bitbucket-sign", '\uf172'),
    ICON_TUMBLR("icon-tumblr", '\uf173'),
    ICON_TUMBLR_SIGN("icon-tumblr-sign", '\uf174'),
    ICON_LONG_ARROW_DOWN("icon-long-arrow-down", '\uf175'),
    ICON_LONG_ARROW_UP("icon-long-arrow-up", '\uf176'),
    ICON_LONG_ARROW_LEFT("icon-long-arrow-left", '\uf177'),
    ICON_LONG_ARROW_RIGHT("icon-long-arrow-right", '\uf178'),
    ICON_APPLE("icon-apple", '\uf179'),
    ICON_WINDOWS("icon-windows", '\uf17a'),
    ICON_ANDROID("icon-android", '\uf17b'),
    ICON_LINUX("icon-linux", '\uf17c'),
    ICON_DRIBBLE("icon-dribble", '\uf17d'),
    ICON_SKYPE("icon-skype", '\uf17e'),
    ICON_FOURSQUARE("icon-foursquare", '\uf180'),
    ICON_TRELLO("icon-trello", '\uf181'),
    ICON_FEMALE("icon-female", '\uf182'),
    ICON_MALE("icon-male", '\uf183'),
    ICON_GITTIP("icon-gittip", '\uf184'),
    ICON_SUN("icon-sun", '\uf185'),
    ICON_MOON("icon-moon", '\uf186'),
    ICON_ARCHIVE("icon-archive", '\uf187'),
    ICON_BUG("icon-bug", '\uf188'),
    ICON_VK("icon-vk", '\uf189'),
    ICON_WEIBO("icon-weibo", '\uf18a'),
    ICON_RENREN("icon-renren", '\uf18b');

    public static FontAwesome findByDescription(String description) {
        if (GriffonNameUtils.isBlank(description)) {
            throw new IllegalArgumentException("Icon description cannot be null!");
        }
        for (FontAwesome font : values()) {
            if (font.getDescription().equals(description)) {
                return font;
            }
        }
        throw new IllegalArgumentException("Icon description " + description + " is invalid!");
    }

    private String description;
    private char code;

    FontAwesome(String description, char code) {
        this.description = description;
        this.code = code;
    }

    public String getDescription() {
        return description;
    }

    public char getCode() {
        return code;
    }
}